/** One-way import of the merged official main, with explicitly selected local photos. */
import { readFile, writeFile, mkdir, copyFile, rm } from "node:fs/promises";
import sharp from "sharp";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { load } from "cheerio";
import {
  addedSlugs,
  deferred,
  snapshotSchema,
  type Project,
} from "../lib/project";

const root = path.resolve("..");
const local = process.env.HQ_PHOTO_SOURCE_ROOT;
if (!local)
  throw new Error(
    "Set HQ_PHOTO_SOURCE_ROOT to the checkout containing approved individual photographs.",
  );
const rows = JSON.parse(
  await readFile("content/notion-metadata.json", "utf8"),
) as Record<string, unknown>[];
const confirmed = JSON.parse(
  await readFile("content/area-confirmed.json", "utf8"),
) as Record<string, number>;
const translatedDescriptions = JSON.parse(
  await readFile("content/project-description-en.json", "utf8"),
) as Record<string, string>;
const pages = [
  "index",
  "projects",
  "services",
  "about",
  "contact",
  "careers",
  "local-partner-international-pm",
  "faq",
];
await mkdir("content/generated", { recursive: true });
// This directory is generated by this importer; source masters stay in the original checkout.
await rm("public/assets", { recursive: true, force: true });
await mkdir("public/assets/css", { recursive: true });
await copyFile(
  path.join(root, "assets/css/style.css"),
  "public/assets/css/main.css",
);
const assetSources = new Map<string, string>();
function url(value: string, file: string) {
  if (!value || /^(?:#|https?:|mailto:|tel:|data:)/.test(value)) return value;
  const parsed = new URL(value, "https://www.hqdesign.tw/" + file);
  if (parsed.pathname.startsWith("/assets/"))
    assetSources.set(parsed.pathname, path.join(root, parsed.pathname));
  parsed.pathname = parsed.pathname
    .replace(/\/index\.html$/, "/")
    .replace(/\.html$/, "");
  return parsed.pathname + parsed.search + parsed.hash;
}
function normalize(html: string, file: string) {
  const $ = load(html, {}, false);
  $("script").remove();
  $("[href], [src]").each((_, el) => {
    for (const attr of ["href", "src"]) {
      const v = $(el).attr(attr);
      if (v) $(el).attr(attr, url(v, file));
    }
  });
  $("[style]").each((_, el) => {
    $(el).attr("style", css($(el).attr("style")!, file));
  });
  $("label").each((i, el) => {
    const input = $(el).parent().find("input, select, textarea").first();
    const id = input.attr("id") || `field-${i}`;
    if (input.length) {
      input.attr("id", id);
      $(el).attr("for", id);
    }
  });
  $("iframe").each((_, el) => {
    if (!$(el).attr("title")) $(el).attr("title", "HQ Design location");
  });
  return $.html();
}
function schemaUrls(value: unknown): unknown {
  if (
    typeof value === "string" &&
    value.startsWith("https://www.hqdesign.tw/")
  ) {
    const target = new URL(value);
    target.pathname = target.pathname
      .replace(/\/index\.html$/, "/")
      .replace(/\.html$/, "");
    return target.href;
  }
  if (Array.isArray(value)) return value.map(schemaUrls);
  if (value && typeof value === "object")
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, schemaUrls(item)]),
    );
  return value;
}
function css(value: string, file: string) {
  return value.replace(
    /url\((['"]?)([^)'"\s]+)\1\)/g,
    (_, q, v) => `url('${url(v, file)}')`,
  );
}
const content: Record<string, unknown> = {};
const chrome: Record<string, unknown> = {};
for (const locale of ["en", "zh"]) {
  for (const page of pages) {
    const file = `${locale === "zh" ? "zh/" : ""}${page}.html`;
    const $ = load(await readFile(path.join(root, file), "utf8"));
    const jsonLd = $('script[type="application/ld+json"]')
      .map((_, e) => schemaUrls(JSON.parse($(e).text())))
      .get();
    const styles = $("style")
      .map((_, e) => css($(e).text(), file))
      .get()
      .join("\n");
    const title = $("title").text();
    const description = $('meta[name="description"]').attr("content") || "";
    if (page === "index")
      chrome[locale] = {
        brand: normalize($(".nav-logo").prop("outerHTML") || "", file),
        nav: normalize($(".nav").prop("outerHTML") || "", file),
        footer: normalize($(".footer").prop("outerHTML") || "", file),
      };
    $(".nav, .footer, script, style").remove();
    if (page === "index") {
      $(".projects-grid").replaceWith(
        '<div data-component="featured-projects"></div>',
      );
      $("a").each((_, el) => {
        if (/View All \d+ Projects/.test($(el).text()))
          $(el).text("View All Projects →");
      });
    }
    if (page === "projects") {
      $(".filter-tabs, .project-filters, .filter-bar").remove();
      $(".filter-btn").parent().remove();
      $(".projects-grid").replaceWith(
        '<div data-component="projects-browser"></div>',
      );
    }
    content[locale + "/" + page] = {
      title,
      description,
      styles,
      jsonLd: page === "projects" ? [] : jsonLd,
      html: normalize($("body").html() || "", file),
    };
  }
}
const listing = load(await readFile(path.join(root, "projects.html"), "utf8"));
const existing = listing(".project-link")
  .map((_, e) => path.basename(listing(e).attr("href")!, ".html"))
  .get();
const slugs = [...new Set([...existing, ...addedSlugs])].filter(
  (s) => !deferred.has(s),
);
const projects: Project[] = [];
const sourceReport: unknown[] = [];
for (const [order, slug] of slugs.entries()) {
  const row = rows.find((r) => r.Slug === slug);
  if (!row) throw new Error("Missing Notion metadata: " + slug);
  const isNew = addedSlugs.includes(slug);
  const from = isNew ? local : root;
  const $en = load(
    await readFile(path.join(from, `projects/${slug}.html`), "utf8"),
  );
  const $zh = isNew
    ? $en
    : load(await readFile(path.join(root, `zh/projects/${slug}.html`), "utf8"));
  const $selected = load(
    await readFile(path.join(local, `projects/${slug}.html`), "utf8"),
  );
  const hero =
    $selected(".proj-hero-img").attr("src") ||
    $en(".proj-hero-img").attr("src");
  const imagePaths = [
    ...new Set([
      hero,
      ...$selected(".gallery-item img, .gallery-grid img")
        .map((_, e) => $selected(e).attr("src"))
        .get(),
    ]),
  ].filter(Boolean) as string[];
  const name = {
    en: String(row["Name En"] || $en("h1").text()),
    zh: String(row["Name Zh"] || $zh("h1").text()),
  };
  const images = imagePaths.map((src, i) => {
    const clean = new URL(src, `https://www.hqdesign.tw/projects/${slug}.html`)
      .pathname;
    assetSources.set(clean, path.join(local, clean));
    return {
      src: clean,
      assetName: path.basename(clean),
      alt: { en: `${name.en} — ${i + 1}`, zh: `${name.zh} — ${i + 1}` },
      kind: /floorplan/i.test(src) ? ("plan" as const) : ("image" as const),
    };
  });
  // The disputed Polytron second image is never introduced; source gallery remains intact.
  const description = {
    en: String(
      row["Description En"] ||
        $en(".overview-desc, .proj-desc-en").first().text() ||
        translatedDescriptions[slug] ||
        "",
    ),
    zh: String(
      row["Description Zh"] ||
        $zh(".overview-desc, .proj-desc-zh").first().text(),
    ),
  };
  for (const key of ["en", "zh"] as const)
    description[key] = description[key]
      .replace(/以下為 AI 編修設計視覺[^。]*。?/g, "")
      .trim();
  const area =
    typeof row["Area Sqm"] === "number"
      ? row["Area Sqm"]
      : (confirmed[slug] ?? null);
  projects.push({
    slug,
    name,
    description,
    images,
    category: String(row.Category || "office"),
    location: {
      en: String(row.Location || ""),
      zh: String(row["Location Zh"] || ""),
    },
    client: {
      en: String(row["Client En"] || ""),
      zh: String(row.Client || ""),
    },
    areaSqm: area,
    year: typeof row.Year === "number" ? row.Year : null,
    order: typeof row["Sort Order"] === "number" ? row["Sort Order"] : order,
    featuredOrder: [
      "secom-nangang-complex",
      "csun",
      "aiontech",
      "kimpton",
    ].indexOf(slug),
    featured: ["secom-nangang-complex", "csun", "aiontech", "kimpton"].includes(
      slug,
    ),
  });
  sourceReport.push({
    slug,
    images: images.map((i) => i.src),
    areaSource:
      row["Area Sqm"] != null
        ? "Notion Area Sqm"
        : confirmed[slug] != null
          ? "User screenshot 2026-09-23"
          : "Missing",
    metadataSource: "Notion",
    photoSource: "Approved local individual image selection",
  });
}
const projectCss = load(
  await readFile(path.join(root, "projects/csun.html"), "utf8"),
)("style").text();
await writeFile("content/generated/project.css", projectCss.trim() + "\n");
await writeFile(
  "content/generated/pages.json",
  JSON.stringify(content, null, 2),
);
await writeFile(
  "content/generated/chrome.json",
  JSON.stringify(chrome, null, 2),
);
await writeFile(
  "content/generated/source-report.json",
  JSON.stringify(
    {
      main: execFileSync("git", ["rev-parse", "origin/main"], {
        cwd: root,
        encoding: "utf8",
      }).trim(),
      projects: sourceReport,
    },
    null,
    2,
  ),
);
const snapshot = snapshotSchema.parse({
  version: "initial-20260923",
  createdAt: new Date().toISOString(),
  projects: projects.sort((a, b) => a.order - b.order),
});
await writeFile(
  "content/initial-release.json",
  JSON.stringify(snapshot, null, 2),
);
for (const [destination, source] of assetSources) {
  const target = path.join("public", destination);
  await mkdir(path.dirname(target), { recursive: true });
  if (/\.(?:jpe?g)$/i.test(target))
    await sharp(source)
      .rotate()
      .resize({
        width: 2400,
        height: 2400,
        fit: "inside",
        withoutEnlargement: true,
      })
      .jpeg({ quality: 85, mozjpeg: true })
      .toFile(target);
  else await copyFile(source, target);
}
console.log(
  `Imported ${Object.keys(content).length} pages and ${projects.length} projects; copied ${assetSources.size} referenced individual assets.`,
);
